version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm i
 #     - run: npm run deploy-production
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y python-pip libyaml-dev python-dev jq
            sudo pip install awscli